### ISSUE TITLE
not compressing some files node_modules?

### ISSUE THREAD

**Issue by agowa** [philnash/jekyll-gzip#10]
I'm also using the jekyll-node-module plugin and it appears that files copied by that plugin aren't compressed. Even though that plugin is executed first.

This plugin correctly generates the compressed files for everything except the files that are copied (e.g. `/assets/webfonts`). At least the svg and eot files in there should be compressed, but currently aren't. No such problem with the files that module places in `/assets/js` or `/assets/css`.
Also if I place another svg file manually in that location e.g. `/assets/webfonts/test.svg` the gzip files are created correctly, but only for that one specific file. The files that the module copied there are still ignored.

When using `--verbose` I can also see that the copying happens before jekyll-gzip is invoked.

_config.yml:
```
plugins:
  - jekyll-node-module
  - jekyll-minifier
  - jekyll-brotli
  - jekyll-gzip

node_modules:
  assets:
    js: assets/js
    css: assets/css
  copy:
    - source: '@fortawesome/fontawesome-free/webfonts/'
      target: assets/webfonts
```
